# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S %Z)(local)} - {l}[{M}][{f}:{L}]:  {m}{n})}"

  # An appender named "requests" that writes to a file with a custom pattern encoder
  requests:
    kind: rolling_file
    path: "log/log.log"
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S %Z)(local)} - {l}[{M}][{f}:{L}]:  {m}{n})}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: "log/log-{}.log"
        base: 1
        count: 5

# Set the default logging level to "warn" and attach the "stdout" appender to the root
root:
  level: debug
  appenders:
    - stdout
    - requests

loggers:
  # Raise the maximum log level for events sent to the "app::backend::db" logger to "info"
  app::backend::db:
    level: info

  # Route log events sent to the "app::requests" logger to the "requests" appender,
  # and *not* the normal appenders installed at the root
  app::requests:
    level: info
    appenders:
      - requests
    additive: false
